name: Test and Deploy to Staging

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install python-dotenv

      - name: Wait for MongoDB
        run: |
          for i in {1..30}; do
            nc -z mongo 27017 && echo "MongoDB is up!" && break
            echo "Waiting for MongoDB..."
            sleep 1
          done

      - name: Run tests
        env:
          FLASK_ENV: test
          MONGO_URI: mongodb://mongo:27017/testdb
        run: |
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv

      - name: Sync databases
        run: |
          chmod +x sync_db.sh
          ./sync_db.sh

      - name: Deploy to Staging
        run: |
          docker-compose -f docker-compose.yml up -d app-staging mongo-staging